(load "fractal-core.scm")
(load "fractal-tokenizer.scm")

(define decoration-table (make-hash-table))
(define style-table      (make-hash-table))

(define %fractaldsl-registry (make-hash-table))

(define (fractaldsl-register! kind name)
  (let ((key (cons kind name)))
    (if (hash-ref %fractaldsl-registry key #f)
        (error (string-append "FractalDSL: " (symbol->string kind)
                               " já definido(a) com esse nome — escolha outro:")
               name)
        (hash-set! %fractaldsl-registry key #t))))

(define (register-defines! indexed)
  (for-each
    (lambda (node)
      (if (and (= (car node) 0) (equal? (cadr node) "define"))
          (let* ((kind    (caddr node))
                 (name    (cadddr node))
                 (subtree (direct-children (cdr (member node indexed eq?)) 0)))
            (cond
              ((equal? kind "decoration")
               (fractaldsl-register! 'decoration name)
               (hash-set! decoration-table name subtree))
              ((equal? kind "style")
               (fractaldsl-register! 'style name)
               (hash-set! style-table name subtree))
              (else
               (error "FractalDSL: 'define' desconhecido (use 'decoration' ou 'style'):" kind))))))
    indexed))

(define coastline-param-keys '("points" "radius" "roughness" "depth" "decorate"))

(define (find-child children key)
  (find (lambda (c) (equal? (cadr c) key)) children))

(define (child-str children key default)
  (let ((n (find-child children key)))
    (if n (caddr n) default)))

(define (ifs-shaped-node? node all-nodes)
  (let* ((ind      (car node))
         (children (direct-children (cdr (member node all-nodes eq?)) ind)))
    (find (lambda (c) (equal? (cadr c) "affine")) children)))

(define (resolve-coastline-children children ind)
  (let ((ext-node (find (lambda (c) (equal? (cadr c) "extends")) children)))
    (if (not ext-node)
        children
        (let* ((style-name (caddr ext-node))
               (base-full  (hash-ref style-table style-name #f)))
          (if (not base-full)
              (error "FractalDSL: style não encontrado:" style-name))
          (let* ((base-shallow  (shallow-children base-full 0))
                 (local-shallow (shallow-children children ind)))
            (apply append
              (map (lambda (key)
                     (if (find (lambda (n) (equal? (cadr n) key)) local-shallow)
                         (extract-block children local-shallow key)
                         (extract-block base-full base-shallow key)))
                   coastline-param-keys)))))))

(define (build-affine-node node)
  (let ((nums (map string->number (cddr node))))
    `(transform ,(car nums) (affine ,@(cdr nums)))))

(define (build-transform-node node all-nodes)
  (let* ((prob     (string->number (caddr node)))
         (ind      (car node))
         (children (direct-children (cdr (member node all-nodes eq?)) ind))
         (depth-node  (find (lambda (c) (equal? (cadr c) "depth")) children))
         (depth    (if depth-node
                       (string->number (caddr depth-node))
                       #f))
         (sub-node (find (lambda (c) (ifs-shaped-node? c children)) children))
         (ifs-expr (build-ifs-node sub-node all-nodes)))
    (if depth
        `(transform ,prob (with-depth ,depth ,ifs-expr))
        `(transform ,prob ,ifs-expr))))

(define (build-ifs-node node all-nodes)
  (let* ((name  (cadr node))
         (fname (cond ((equal? name "sierpinski") "Sierpinski")
                      ((equal? name "barnsley")   "BarnsleyFern")
                      (else name)))
         (ind      (car node))
         (rest     (cdr (member node all-nodes eq?)))  ; everything after this node
         (children (direct-children rest ind))
         (affines  (filter (lambda (c) (equal? (cadr c) "affine")) children)))
    `(ifs (create-fractal ,fname)
       ,@(map build-affine-node affines))))

(define (build-decorate-from-subtree subtree)
  (let* ((find-node       (lambda (key) (find (lambda (c) (equal? (cadr c) key)) subtree)))
         (use-nodes       (filter (lambda (c) (equal? (cadr c) "use")) subtree))
         (fref-nodes      (filter (lambda (c) (equal? (cadr c) "use-fractal")) subtree))
         (local-frefs     (map (lambda (n) (cons (string->number (cadddr n)) (caddr n))) fref-nodes)))
    (if (pair? use-nodes)
        (let* ((bases (map (lambda (u)
                              (let* ((nm (caddr u))
                                     (b  (hash-ref decoration-table nm #f)))
                                (if (not b)
                                    (error "FractalDSL: decoration não encontrada:" nm))
                                (build-decorate-from-subtree b)))
                            use-nodes))
               (first-base       (car bases))
               (composed-transf  (apply append (map (lambda (r) (cdr (assq 'transforms r))) bases)))
               (composed-frefs   (append local-frefs
                                          (apply append (map (lambda (r) (cdr (assq 'fractal-refs r))) bases))))
               (steps-node       (find-node "steps"))
               (scale-node       (find-node "scale"))
               (fill-node        (find-node "fill"))
               (fscale-node      (find-node "fill-scale"))
               (fsteps-node      (find-node "fill-steps"))
               (fradius-node     (find-node "fill-radius")))
          `((steps        . ,(if steps-node  (string->number (caddr steps-node))  (cdr (assq 'steps       first-base))))
            (scale        . ,(if scale-node  (string->number (caddr scale-node))  (cdr (assq 'scale       first-base))))
            (fill         . ,(if fill-node   (string->number (caddr fill-node))   (cdr (assq 'fill        first-base))))
            (fill-scale   . ,(if fscale-node (string->number (caddr fscale-node)) (cdr (assq 'fill-scale  first-base))))
            (fill-steps   . ,(if fsteps-node (string->number (caddr fsteps-node)) (cdr (assq 'fill-steps  first-base))))
            (fill-radius  . ,(if fradius-node(string->number (caddr fradius-node))(cdr (assq 'fill-radius first-base))))
            (transforms   . ,composed-transf)
            (fractal-refs . ,composed-frefs)))
        ;; sem 'use': decoração escrita inline (comportamento original)
        (let* ((steps-node  (find-node "steps"))
               (scale-node  (find-node "scale"))
               (fill-node   (find-node "fill"))
               (fscale-node (find-node "fill-scale"))
               (fsteps-node (find-node "fill-steps"))
               (fradius-node(find-node "fill-radius"))
               (t-nodes     (filter (lambda (c) (equal? (cadr c) "transform")) subtree))
               (steps       (if steps-node  (string->number (caddr steps-node))  60))
               (scale       (if scale-node  (string->number (caddr scale-node))  0.06))
               (fill        (if fill-node   (string->number (caddr fill-node))   #f))
               (fill-scale  (if fscale-node (string->number (caddr fscale-node)) scale))
               (fill-steps  (if fsteps-node (string->number (caddr fsteps-node)) steps))
               (fill-radius (if fradius-node(string->number (caddr fradius-node)) 0.5))
               (transforms  (map (lambda (t) (build-transform-node t subtree)) t-nodes)))
          `((steps        . ,steps)
            (scale        . ,scale)
            (fill         . ,fill)
            (fill-scale   . ,fill-scale)
            (fill-steps   . ,fill-steps)
            (fill-radius  . ,fill-radius)
            (transforms   . ,transforms)
            (fractal-refs . ,local-frefs))))))

(define (build-decorate-node node all-nodes)
  (let* ((ind      (car node))
         (children (direct-children (cdr (member node all-nodes eq?)) ind)))
    (build-decorate-from-subtree children)))

(define (build-coastline-node name all-nodes)
  (let* ((coast-node  (find (lambda (n) (equal? (cadr n) "coastline")) all-nodes))
         (ind         (car coast-node))
         (raw-children (direct-children (cdr (member coast-node all-nodes eq?)) ind))
         (children    (resolve-coastline-children raw-children ind))
         (get-num     (lambda (key default)
                        (let ((n (find (lambda (c) (equal? (cadr c) key)) children)))
                          (if n (string->number (caddr n)) default))))
         (points      (get-num "points"    7))
         (radius      (get-num "radius"    #f))
         (radius-x    (get-num "radius-x"  #f))
         (radius-y    (get-num "radius-y"  #f))
         (rx          (or radius-x radius 1.0))
         (ry          (or radius-y radius 1.0))
         (roughness   (get-num "roughness" 0.4))
         (depth       (get-num "depth"     6))
         (decor-node  (find (lambda (c) (equal? (cadr c) "decorate")) children))
         (iter-node   (find (lambda (n) (equal? (cadr n) "iterations")) all-nodes))
         (iters       (if iter-node (string->number (caddr iter-node)) 10000)))
    (if decor-node
      (let* ((decor        (build-decorate-node decor-node children))
             (steps        (cdr (assq 'steps        decor)))
             (scale        (cdr (assq 'scale        decor)))
             (fill         (cdr (assq 'fill         decor)))
             (fill-scale   (cdr (assq 'fill-scale   decor)))
             (fill-steps   (cdr (assq 'fill-steps   decor)))
             (fill-radius  (cdr (assq 'fill-radius  decor)))
             (transforms   (cdr (assq 'transforms   decor)))
             (fractal-refs (cdr (assq 'fractal-refs decor))))
        `(define ,(string->symbol name)
           (make-filled-island ,name ,iters ,points ,rx ,ry ,roughness ,depth
                                (list ,@transforms) ,steps ,scale
                                ,fill ,fill-scale ,fill-steps ,fill-radius
                                (list ,@(map (lambda (r) `(cons ,(car r) ,(cdr r))) fractal-refs)))))
      `(define ,(string->symbol name)
         (fractal-pipe (create-fractal ,name)
           (set-field 'iterations ,iters)
           (set-field 'coastline
             (list (cons 'points   ,points)
                   (cons 'radius-x ,rx)
                   (cons 'radius-y ,ry)
                   (cons 'roughness ,roughness)
                   (cons 'depth     ,depth))))))))

(define (build-equation-node name all-nodes)
  (let* ((eq-str      (child-str all-nodes "equation" "z=z^2+c"))
         (iters       (string->number (child-str all-nodes "iterations" "100")))
         (zoom-val    (string->number (child-str all-nodes "zoom" "100")))
         (center-node (find-child all-nodes "center"))
         (cre         (if center-node (string->number (caddr center-node)) 0))
         (cim         (if center-node (string->number (cadddr center-node)) 0))
         (res-node    (find-child all-nodes "resolution"))
         (rw          (if res-node (string->number (caddr res-node)) 800))
         (rh          (if res-node (string->number (cadddr res-node)) 800))
         (const-node  (find (lambda (n) (and (equal? (cadr n) "constant")
                                              (equal? (caddr n) "c")))
                             all-nodes))
         (c-re        (and const-node (string->number (cadddr const-node))))
         (c-im        (and const-node (string->number (car (cddddr const-node))))))
    `(define ,(string->symbol name)
       (fractal-pipe (create-fractal ,name)
         (equation ,eq-str)
         (iterations ,iters)
         (center ,cre ,cim)
         (zoom ,zoom-val)
         (set-field 'resolution (list ,rw ,rh))
         ,@(if const-node
               `((constant 'c (make-c ,c-re ,c-im)))
               '())))))

(define (build-fractal name all-nodes)
  (let* ((iter-node (find (lambda (n) (equal? (cadr n) "iterations")) all-nodes))
         (iters     (if iter-node (string->number (caddr iter-node)) 10000))
         (ifs-node  (find (lambda (n) (equal? (cadr n) "ifs")) all-nodes))
         (ifs-ind   (car ifs-node))
         (t-nodes   (filter (lambda (n)
                              (and (equal? (cadr n) "transform")
                                   (> (car n) ifs-ind)))
                            all-nodes))
         (transforms (map (lambda (t)
                            (build-transform-node t all-nodes))
                          t-nodes)))
    `(define ,(string->symbol name)
       (fractal-pipe (create-fractal ,name)
         (set-field 'iterations ,iters)
         (set-field 'ifs (list ,@transforms))))))

(define (get-field-alist alist key)
  (let ((r (assq key alist))) (if r (cdr r) #f)))

(define (build-render-node node all-nodes)
  (let* ((ind        (car node))
         (children   (direct-children (cdr (member node all-nodes eq?)) ind))
         (res-node   (find (lambda (c) (equal? (cadr c) "resolution")) children))
         (color-node (find (lambda (c) (equal? (cadr c) "color")) children))
         (style-node (find (lambda (c) (equal? (cadr c) "style")) children))
         (width      (if res-node (string->number (caddr res-node)) 800))
         (height     (if res-node (string->number (cadddr res-node)) 800))
         (color      (if color-node (caddr color-node) "mono"))
         (style      (if style-node (caddr style-node) "island")))
    (list (cons 'width width) (cons 'height height)
          (cons 'color color) (cons 'style style))))

(define (write-render-config render-cfg out-path)
  (call-with-output-file out-path
    (lambda (port)
      (display "WIDTH=" port)
      (display (get-field-alist render-cfg 'width) port)
      (newline port)
      (display "HEIGHT=" port)
      (display (get-field-alist render-cfg 'height) port)
      (newline port)
      (display "COLOR=" port)
      (display (get-field-alist render-cfg 'color) port)
      (newline port)
      (display "STYLE=" port)
      (display (get-field-alist render-cfg 'style) port)
      (newline port))))
