(load "fractal-core.scm")
(load "fractal-params.scm")
(load "fractal-ifs.scm")
(load "fractal-coastline.scm")
(load "fractal-generate.scm")
(load "fractal-tokenizer.scm")
(load "fractal-dsl-builders.scm")
(load "fractal-render.scm")

(define (run-frac-file filename)
  (let* ((lines      (read-lines filename))
         (indexed    (to-indexed lines))
         (top        (filter (lambda (n) (and (= (car n) 0)
                                                (not (equal? (cadr n) "define"))))
                              indexed))
         (render-cfg #f))
    (register-defines! indexed)
    (for-each
      (lambda (node)
        (let ((kw (cadr node)))
          (cond
            ((equal? kw "fractal")
             (let* ((name (caddr node)))
               (fractaldsl-register! 'fractal name)
               (let* ((children      (direct-children (cdr (member node indexed eq?)) 0))
                      (has-coastline (find (lambda (n) (equal? (cadr n) "coastline")) children))
                      (has-equation  (find (lambda (n) (equal? (cadr n) "equation")) children))
                      (expr          (cond
                                        (has-coastline (build-coastline-node name children))
                                        (has-equation  (build-equation-node name children))
                                        (else          (build-fractal name children)))))
                 (display "Compilando: ") (display name) (newline)
                 (display expr) (newline)
                 (eval expr (interaction-environment)))))
            ((equal? kw "render")
             (let* ((cfg      (build-render-node node indexed))
                    (cfg-path "render.cfg"))
               (set! render-cfg cfg)
               (display "Configurando render: ") (display cfg) (newline)
               (write-render-config cfg cfg-path)))
            ((equal? kw "generate")
             (let* ((name (caddr node))
                    (sym  (string->symbol name))
                    (csv  (string-append (string-downcase name) ".csv"))
                    (png  (string-append (string-downcase name) ".png")))
               (display "Exportando: ") (display csv) (newline)
               (export-csv (eval sym (interaction-environment)) csv)
               (when render-cfg
                (let ((width  (number->string (get-field-alist render-cfg 'width)))
                  (height (number->string (get-field-alist render-cfg 'height)))
                  (color  (get-field-alist render-cfg 'color))
                  (style  (get-field-alist render-cfg 'style)))
                (write-render-config render-cfg "render.cfg")
                (render-csv-and-png! csv png))))
            ))))
      top)))
